version: '3'

services:
  web:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
   image: mysql:5.7
   environment:
    MYSQL_DATABASE: ecommerce
    MYSQL_ROOT_PASSWORD: root
    ports:
     -"3306:3306"
   volumes:
    - ./mysql-data:/docker-entrypoint-initdb.d
volumes:
  db_data:
